"""NT native API syscall dispatcher.

INT 0x2E and SYSENTER both route here. EAX = syscall number; EDX = caller's
stack pointer (INT 0x2E) or ESP already points to args (SYSENTER).

Syscall numbers: Windows XP SP2/SP3 x86-32 (ntoskrnl 5.1.2600).
Reference: KiServiceTable analysis, Fyyre/NTSyscalls, j00ru syscall tables.
If a number seems wrong for your binary, verify against ntoskrnl KiServiceTable.
"""

from __future__ import annotations

from typing import TYPE_CHECKING, Callable

if TYPE_CHECKING:
    from tew.hardware.cpu import CPU
    from tew.hardware.memory import Memory

from tew.hardware.cpu import EAX
from tew.logger import logger

# ── Windows XP SP2/SP3 x86-32 syscall name table ────────────────────────────

_NT_SYSCALL_NAMES: dict[int, str] = {
    0x000: "NtAcceptConnectPort",
    0x001: "NtAccessCheck",
    0x002: "NtAccessCheckAndAuditAlarm",
    0x003: "NtAccessCheckByType",
    0x004: "NtAccessCheckByTypeAndAuditAlarm",
    0x005: "NtAccessCheckByTypeResultList",
    0x006: "NtAccessCheckByTypeResultListAndAuditAlarm",
    0x007: "NtAccessCheckByTypeResultListAndAuditAlarmByHandle",
    0x008: "NtAddAtom",
    0x009: "NtAddBootEntry",
    0x00A: "NtAdjustGroupsToken",
    0x00B: "NtAdjustPrivilegesToken",
    0x00C: "NtAlertResumeThread",
    0x00D: "NtAlertThread",
    0x00E: "NtAllocateLocallyUniqueId",
    0x00F: "NtAllocateUserPhysicalPages",
    0x010: "NtAllocateUuids",
    0x011: "NtAllocateVirtualMemory",
    0x012: "NtAreMappedFilesTheSame",
    0x013: "NtAssignProcessToJobObject",
    0x014: "NtCallbackReturn",
    0x015: "NtCancelDeviceWakeupRequest",
    0x016: "NtCancelIoFile",
    0x017: "NtCancelTimer",
    0x018: "NtClearEvent",
    0x019: "NtClose",
    0x01A: "NtCloseObjectAuditAlarm",
    0x01B: "NtCompactKeys",
    0x01C: "NtCompareTokens",
    0x01D: "NtCompleteConnectPort",
    0x01E: "NtConnectPort",
    0x01F: "NtContinue",
    0x020: "NtCreateDebugObject",
    0x021: "NtCreateDirectoryObject",
    0x022: "NtCreateEvent",
    0x023: "NtCreateEventPair",
    0x024: "NtCreateFile",
    0x025: "NtCreateIoCompletion",
    0x026: "NtCreateJobObject",
    0x027: "NtCreateJobSet",
    0x028: "NtCreateKey",
    0x029: "NtCreateMailslotFile",
    0x02A: "NtCreateMutant",
    0x02B: "NtCreateNamedPipeFile",
    0x02C: "NtCreatePagingFile",
    0x02D: "NtCreatePort",
    0x02E: "NtCreateProcess",
    0x02F: "NtCreateProcessEx",
    0x030: "NtCreateProfile",
    0x031: "NtCreateSection",
    0x032: "NtCreateSemaphore",
    0x033: "NtCreateSymbolicLinkObject",
    0x034: "NtCreateThread",
    0x035: "NtCreateTimer",
    0x036: "NtCreateToken",
    0x037: "NtCreateWaitablePort",
    0x038: "NtDebugActiveProcess",
    0x039: "NtDebugContinue",
    0x03A: "NtDelayExecution",
    0x03B: "NtDeleteAtom",
    0x03C: "NtDeleteBootEntry",
    0x03D: "NtDeleteFile",
    0x03E: "NtDeleteKey",
    0x03F: "NtDeleteObjectAuditAlarm",
    0x040: "NtDeleteValueKey",
    0x041: "NtDeviceIoControlFile",
    0x042: "NtDisplayString",
    0x043: "NtDuplicateObject",
    0x044: "NtDuplicateToken",
    0x045: "NtEnumerateBootEntries",
    0x046: "NtEnumerateKey",
    0x047: "NtEnumerateSystemEnvironmentValuesEx",
    0x048: "NtEnumerateValueKey",
    0x049: "NtExtendSection",
    0x04A: "NtFilterToken",
    0x04B: "NtFindAtom",
    0x04C: "NtFlushBuffersFile",
    0x04D: "NtFlushInstructionCache",
    0x04E: "NtFlushKey",
    0x04F: "NtFlushVirtualMemory",
    0x050: "NtFlushWriteBuffer",
    0x051: "NtFreeUserPhysicalPages",
    0x052: "NtFreeVirtualMemory",
    0x053: "NtFsControlFile",
    0x054: "NtGetContextThread",
    0x055: "NtGetDevicePowerState",
    0x056: "NtGetPlugPlayEvent",
    0x057: "NtGetWriteWatch",
    0x058: "NtImpersonateAnonymousToken",
    0x059: "NtImpersonateClientOfPort",
    0x05A: "NtImpersonateThread",
    0x05B: "NtInitializeRegistry",
    0x05C: "NtInitiatePowerAction",
    0x05D: "NtIsProcessInJob",
    0x05E: "NtIsSystemResumeAutomatic",
    0x05F: "NtListenPort",
    0x060: "NtLoadDriver",
    0x061: "NtLoadKey",
    0x062: "NtLoadKey2",
    0x063: "NtLockFile",
    0x064: "NtLockProductActivationKeys",
    0x065: "NtLockRegistryKey",
    0x066: "NtLockVirtualMemory",
    0x067: "NtMakePermanentObject",
    0x068: "NtMakeTemporaryObject",
    0x069: "NtMapUserPhysicalPages",
    0x06A: "NtMapUserPhysicalPagesScatter",
    0x06B: "NtMapViewOfSection",
    0x06C: "NtModifyBootEntry",
    0x06D: "NtNotifyChangeDirectoryFile",
    0x06E: "NtNotifyChangeKey",
    0x06F: "NtNotifyChangeMultipleKeys",
    0x070: "NtOpenDirectoryObject",
    0x071: "NtOpenEvent",
    0x072: "NtOpenEventPair",
    0x073: "NtOpenFile",
    0x074: "NtOpenIoCompletion",
    0x075: "NtOpenJobObject",
    0x076: "NtOpenKey",
    0x077: "NtOpenMutant",
    0x078: "NtOpenObjectAuditAlarm",
    0x079: "NtOpenProcess",
    0x07A: "NtOpenProcessToken",
    0x07B: "NtOpenProcessTokenEx",
    0x07C: "NtOpenSection",
    0x07D: "NtOpenSemaphore",
    0x07E: "NtOpenSymbolicLinkObject",
    0x07F: "NtOpenThread",
    0x080: "NtOpenThreadToken",
    0x081: "NtOpenThreadTokenEx",
    0x082: "NtOpenTimer",
    0x083: "NtPlugPlayControl",
    0x084: "NtPowerInformation",
    0x085: "NtPrivilegeCheck",
    0x086: "NtPrivilegeObjectAuditAlarm",
    0x087: "NtPrivilegedServiceAuditAlarm",
    0x088: "NtProtectVirtualMemory",
    0x089: "NtPulseEvent",
    0x08A: "NtQueryAttributesFile",
    0x08B: "NtQueryBootEntryOrder",
    0x08C: "NtQueryBootOptions",
    0x08D: "NtQueryDebugFilterState",
    0x08E: "NtQueryDefaultLocale",
    0x08F: "NtQueryDefaultUILanguage",
    0x090: "NtQueryDirectoryFile",
    0x091: "NtQueryDirectoryObject",
    0x092: "NtQueryEaFile",
    0x093: "NtQueryEvent",
    0x094: "NtQueryFullAttributesFile",
    0x095: "NtQueryInformationAtom",
    0x096: "NtQueryInformationFile",
    0x097: "NtQueryInformationJobObject",
    0x098: "NtQueryInformationPort",
    0x099: "NtQueryInformationProcess",
    0x09A: "NtQueryInformationThread",
    0x09B: "NtQueryInformationToken",
    0x09C: "NtQueryInstallUILanguage",
    0x09D: "NtQueryIntervalProfile",
    0x09E: "NtQueryIoCompletion",
    0x09F: "NtQueryKey",
    0x0A0: "NtQueryMultipleValueKey",
    0x0A1: "NtQueryMutant",
    0x0A2: "NtQueryObject",
    0x0A3: "NtQueryOpenSubKeys",
    0x0A4: "NtQueryPerformanceCounter",
    0x0A5: "NtQueryPortInformationProcess",
    0x0A6: "NtQueryQuotaInformationFile",
    0x0A7: "NtQuerySection",
    0x0A8: "NtQuerySecurityObject",
    0x0A9: "NtQuerySemaphore",
    0x0AA: "NtQuerySymbolicLinkObject",
    0x0AB: "NtQuerySystemEnvironmentValue",
    0x0AC: "NtQuerySystemEnvironmentValueEx",
    0x0AD: "NtQuerySystemInformation",
    0x0AE: "NtQuerySystemTime",
    0x0AF: "NtQueryTimer",
    0x0B0: "NtQueryTimerResolution",
    0x0B1: "NtQueryValueKey",
    0x0B2: "NtQueryVirtualMemory",
    0x0B3: "NtQueryVolumeInformationFile",
    0x0B4: "NtQueueApcThread",
    0x0B5: "NtRaiseException",
    0x0B6: "NtRaiseHardError",
    0x0B7: "NtReadFile",
    0x0B8: "NtReadFileScatter",
    0x0B9: "NtReadRequestData",
    0x0BA: "NtReadVirtualMemory",
    0x0BB: "NtRegisterThreadTerminatePort",
    0x0BC: "NtReleaseMutant",
    0x0BD: "NtReleaseKeyedEvent",
    0x0BE: "NtReleaseSemaphore",
    0x0BF: "NtReleaseWorkerFactoryWorker",
    0x0C0: "NtRemoveIoCompletion",
    0x0C1: "NtRemoveProcessDebug",
    0x0C2: "NtRenameKey",
    0x0C3: "NtReplaceKey",
    0x0C4: "NtReplyPort",
    0x0C5: "NtReplyWaitReceivePort",
    0x0C6: "NtReplyWaitReceivePortEx",
    0x0C7: "NtReplyWaitReplyPort",
    0x0C8: "NtRequestDeviceWakeup",
    0x0C9: "NtRequestPort",
    0x0CA: "NtRequestWaitReplyPort",
    0x0CB: "NtRequestWakeupLatency",
    0x0CC: "NtResetEvent",
    0x0CD: "NtResetWriteWatch",
    0x0CE: "NtRestoreKey",
    0x0CF: "NtResumeProcess",
    0x0D0: "NtResumeThread",
    0x0D1: "NtSaveKey",
    0x0D2: "NtSaveKeyEx",
    0x0D3: "NtSaveMergedKeys",
    0x0D4: "NtSecureConnectPort",
    0x0D5: "NtSetBootEntryOrder",
    0x0D6: "NtSetBootOptions",
    0x0D7: "NtSetContextThread",
    0x0D8: "NtSetDebugFilterState",
    0x0D9: "NtSetDefaultHardErrorPort",
    0x0DA: "NtSetDefaultLocale",
    0x0DB: "NtSetDefaultUILanguage",
    0x0DC: "NtSetEaFile",
    0x0DD: "NtSetEvent",
    0x0DE: "NtSetEventBoostPriority",
    0x0DF: "NtSetHighEventPair",
    0x0E0: "NtSetHighWaitLowEventPair",
    0x0E1: "NtSetInformationDebugObject",
    0x0E2: "NtSetInformationFile",
    0x0E3: "NtSetInformationJobObject",
    0x0E4: "NtSetInformationKey",
    0x0E5: "NtSetInformationObject",
    0x0E6: "NtSetInformationProcess",
    0x0E7: "NtSetInformationThread",
    0x0E8: "NtSetInformationToken",
    0x0E9: "NtSetIntervalProfile",
    0x0EA: "NtSetIoCompletion",
    0x0EB: "NtSetLdtEntries",
    0x0EC: "NtSetLowEventPair",
    0x0ED: "NtSetLowWaitHighEventPair",
    0x0EE: "NtSetQuotaInformationFile",
    0x0EF: "NtSetSecurityObject",
    0x0F0: "NtSetSystemEnvironmentValue",
    0x0F1: "NtSetSystemEnvironmentValueEx",
    0x0F2: "NtSetSystemInformation",
    0x0F3: "NtSetSystemPowerState",
    0x0F4: "NtSetSystemTime",
    0x0F5: "NtSetThreadExecutionState",
    0x0F6: "NtSetTimer",
    0x0F7: "NtSetTimerResolution",
    0x0F8: "NtSetUuidSeed",
    0x0F9: "NtSetValueKey",
    0x0FA: "NtSetVolumeInformationFile",
    0x0FB: "NtShutdownSystem",
    0x0FC: "NtSignalAndWaitForSingleObject",
    0x0FD: "NtStartProfile",
    0x0FE: "NtStopProfile",
    0x0FF: "NtSuspendProcess",
    0x100: "NtSuspendThread",
    0x101: "NtSystemDebugControl",
    0x102: "NtTerminateJobObject",
    0x103: "NtTerminateProcess",
    0x104: "NtTerminateThread",
    0x105: "NtTestAlert",
    0x106: "NtTraceEvent",
    0x107: "NtTranslateFilePath",
    0x108: "NtUnloadDriver",
    0x109: "NtUnloadKey",
    0x10A: "NtUnloadKey2",
    0x10B: "NtUnloadKeyEx",
    0x10C: "NtUnlockFile",
    0x10D: "NtUnlockVirtualMemory",
    0x10E: "NtUnmapViewOfSection",
    0x10F: "NtVdmControl",
    0x110: "NtWaitForDebugEvent",
    0x111: "NtWaitForKeyedEvent",
    0x112: "NtWaitForMultipleObjects",
    0x113: "NtWaitForSingleObject",
    0x114: "NtWaitHighEventPair",
    0x115: "NtWaitLowEventPair",
    0x116: "NtWriteFile",
    0x117: "NtWriteFileGather",
    0x118: "NtWriteRequestData",
    0x119: "NtWriteVirtualMemory",
    0x11A: "NtYieldExecution",
    0x11B: "NtCreateKeyedEvent",
    0x11C: "NtOpenKeyedEvent",
}

NtSyscallHandler = Callable[["CPU", "Memory"], None]


class NtSyscallDispatcher:
    """Dispatches NT native API calls arriving via INT 0x2E or SYSENTER.

    Handlers are registered per syscall number and receive (cpu, memory).
    They must set cpu.regs[EAX] to the NTSTATUS return value before returning.
    Unregistered syscalls raise RuntimeError with the name from the XP table.
    """

    def __init__(self, memory: "Memory") -> None:
        self._memory = memory
        self._handlers: dict[int, NtSyscallHandler] = {}

    def register(self, syscall_num: int, handler: NtSyscallHandler) -> None:
        self._handlers[syscall_num] = handler

    def dispatch(self, cpu: "CPU") -> None:
        num = cpu.regs[EAX] & 0xFFFFFFFF
        name = _NT_SYSCALL_NAMES.get(num, f"Unknown_0x{num:x}")
        logger.debug("nt", f"NT syscall 0x{num:03x} ({name}) EIP=0x{cpu.eip & 0xFFFFFFFF:08x}")
        handler = self._handlers.get(num)
        if handler is not None:
            handler(cpu, self._memory)
        else:
            raise RuntimeError(
                f"NT syscall 0x{num:03x} ({name}) not implemented"
                f" at EIP=0x{cpu.eip & 0xFFFFFFFF:08x}"
            )
